#!/bin/bash

apt-get update
apt-get install qbittorrent-nox

useradd -r -M -d /nonexistent -s /usr/sbin/nologin qbittorrent

tee /etc/systemd/system/qbittorrent.service > /dev/null <EOF
[Unit]
Description=qBittorrent-nox
After=network.target

[Service]
User=qbittorrent
Group=qbittorrent
ExecStart=/usr/bin/qbittorrent-nox
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now qbittorrent

~/.config/qBittorrent/qBittorrent.conf

systemctl restart qbittorrent.service

sudo chown -R qbittorrent:qbittorrent /mnt/disk1/
